"""
WebShop predicates (mixed_fine, behavioral, Gemini 3.1 Pro). Auto-generated by route_d_pipeline.py
"""

from typing import Callable

import re

def check_search_interface(observation: str) -> bool:
    """
    Detects if the agent is at the initial search interface.
    This is the starting point for most tasks where the agent needs to enter a search query.
    """
    # Matches 'search' with optional non-alphabetic characters (like quotes) around it
    return re.search(r"^[^a-z]*search[^a-z]*$", observation.strip(), re.IGNORECASE) is not None

def check_back_to_search_available(observation: str) -> bool:
    """
    Detects if the agent has navigated away from the initial search page and can now return to it.
    This indicates the agent successfully executed a search or clicked a product.
    """
    return re.search(r'\bback to search\b', observation, re.IGNORECASE) is not None

def check_search_results_header(observation: str) -> bool:
    """
    Detects if the agent has reached the search results page.
    The presence of 'total results' indicates the search engine returned matching items.
    """
    return re.search(r'\btotal results\b', observation, re.IGNORECASE) is not None

def check_search_results_pagination(observation: str) -> bool:
    """
    Detects if the search results page includes pagination controls ('Next'), 
    indicating the agent can navigate through multiple pages of products.
    """
    return re.search(r'\bnext\b', observation, re.IGNORECASE) is not None

def check_search_results_products(observation: str) -> bool:
    """
    Detects if the search results actually contain product listings.
    Matches the standard Amazon ASIN format (e.g., B01EX1BWE4) which appears in the results.
    """
    return re.search(r'\bb0[a-z0-9]{8}\b', observation, re.IGNORECASE) is not None

def check_search_results_prices(observation: str) -> bool:
    """
    Detects if the agent can see product prices in the search results,
    which is necessary for filtering items based on price constraints.
    """
    return re.search(r'\$\d+\.\d+', observation) is not None

def check_product_page_navigation(observation: str) -> bool:
    """
    Detects if the agent has clicked on a specific product and reached its details page.
    The 'Prev' button is a distinct navigational element of the product page.
    """
    return re.search(r'\bprev\b', observation, re.IGNORECASE) is not None

def check_product_page_price(observation: str) -> bool:
    """
    Detects if the agent is viewing the specific price of the selected product,
    ensuring it can verify the price constraint before purchasing.
    """
    return re.search(r'\bprice\b', observation, re.IGNORECASE) is not None

def check_product_page_rating(observation: str) -> bool:
    """
    Detects if the agent is viewing the product's rating information,
    which is part of the standard product details layout.
    """
    return re.search(r'\brating\b', observation, re.IGNORECASE) is not None

def check_product_page_details_tabs(observation: str) -> bool:
    """
    Detects if the agent has access to the Description, Features, and Reviews tabs
    on the product page, which contain detailed information about the item.
    """
    obs = observation.lower()
    return (re.search(r'\bdescription\b', obs) is not None and 
            re.search(r'\bfeatures\b', obs) is not None and 
            re.search(r'\breviews\b', obs) is not None)

def check_product_page_buy_button(observation: str) -> bool:
    """
    Detects if the 'Buy Now' button is visible on the product page.
    This is the final required element the agent must see to complete the task.
    """
    return re.search(r'\bbuy now\b', observation, re.IGNORECASE) is not None


CHECKPOINTS = [
    check_search_interface,
    check_back_to_search_available,
    check_search_results_header,
    check_search_results_pagination,
    check_search_results_products,
    check_search_results_prices,
    check_product_page_navigation,
    check_product_page_price,
    check_product_page_rating,
    check_product_page_details_tabs,
    check_product_page_buy_button
]

CHECKPOINT_DESCRIPTIONS = [
    "Agent is at the initial search interface.",
    "Agent has navigated away from the start page and can return to search.",
    "Agent sees the search results header with total results count.",
    "Agent sees pagination controls on the search results page.",
    "Agent sees product ASINs in the search results.",
    "Agent sees product prices in the search results.",
    "Agent has navigated to a specific product page.",
    "Agent sees the specific price of the selected product.",
    "Agent sees the rating of the selected product.",
    "Agent sees the detailed information tabs (Description, Features, Reviews).",
    "Agent sees the 'Buy Now' button to complete the purchase."
]

def get_webshop_checkpoints() -> list[Callable[[str], bool]]:
    return CHECKPOINTS.copy()

def describe_checkpoints() -> list[tuple[str, str]]:
    return list(zip([f.__name__ for f in CHECKPOINTS], CHECKPOINT_DESCRIPTIONS))

