"""
WebShop predicates (success_only_fine, behavioral, Gemini 3.1 Pro). Auto-generated by route_d_pipeline.py
"""


import re
from typing import Callable

# Predicate functions (ordered by expected progression)

def check_search_capability(observation: str) -> bool:
    """P1: Detects if the agent is in a state where search is possible (either the initial search screen or having a 'Back to Search' option). This is the foundational navigational capability."""
    return 'search' in observation.lower()

def check_search_results_page(observation: str) -> bool:
    """P2: Detects if the agent has successfully executed a search query and reached the search results page, indicated by the presence of a total results count."""
    return 'total results:' in observation.lower()

def check_pagination_available(observation: str) -> bool:
    """P3: Detects if the search results page has pagination available, showing that the agent retrieved a multi-page list of products."""
    return 'next >' in observation.lower()

def check_product_list_visible(observation: str) -> bool:
    """P4: Detects the presence of product ASINs (e.g., B01EX1BWE4) in the observation, indicating the agent is viewing actual product listings."""
    return bool(re.search(r'\bB0[A-Z0-9]{8}\b', observation, re.IGNORECASE))

def check_product_prices_visible(observation: str) -> bool:
    """P5: Detects the presence of formatted prices (e.g., $99.99) in the observation, showing the agent is viewing cost information."""
    return bool(re.search(r'\$\d+\.\d+', observation))

def check_item_page_navigation(observation: str) -> bool:
    """P6: Detects if the agent has clicked on a specific product and navigated to its detailed item page, indicated by the '< Prev' navigation button."""
    return '< prev' in observation.lower()

def check_item_options_visible(observation: str) -> bool:
    """P7: Detects if the agent is viewing an item that has selectable attributes (like size, color, or flavor), which are necessary for specifying the exact product variation."""
    return bool(re.search(r'\b(size|color|flavor name)\b', observation, re.IGNORECASE))

def check_item_price_details(observation: str) -> bool:
    """P8: Detects if the agent is viewing the specific price details of an individual item, indicated by the 'Price:' label on the item page."""
    return 'price:' in observation.lower()

def check_item_rating_visible(observation: str) -> bool:
    """P9: Detects if the agent is viewing the rating information of the selected item."""
    return 'rating:' in observation.lower()

def check_item_description_visible(observation: str) -> bool:
    """P10: Detects if the agent has access to the detailed text description of the item."""
    return 'description' in observation.lower()

def check_item_features_visible(observation: str) -> bool:
    """P11: Detects if the agent has access to the bulleted features list of the item."""
    return 'features' in observation.lower()

def check_item_reviews_visible(observation: str) -> bool:
    """P12: Detects if the agent has access to the customer reviews section of the item."""
    return 'reviews' in observation.lower()

def check_buy_now_visible(observation: str) -> bool:
    """P13: Detects if the agent has reached a state where the 'Buy Now' button is visible, indicating it is in a position to complete the purchase."""
    return 'buy now' in observation.lower()


# Ordered list of all checkpoints
CHECKPOINTS: list[Callable[[str], bool]] = [
    check_search_capability,
    check_search_results_page,
    check_pagination_available,
    check_product_list_visible,
    check_product_prices_visible,
    check_item_page_navigation,
    check_item_options_visible,
    check_item_price_details,
    check_item_rating_visible,
    check_item_description_visible,
    check_item_features_visible,
    check_item_reviews_visible,
    check_buy_now_visible
]

CHECKPOINT_DESCRIPTIONS: list[str] = [
    "P1: Detects if the agent is in a state where search is possible (either the initial search screen or having a 'Back to Search' option). This is the foundational navigational capability.",
    "P2: Detects if the agent has successfully executed a search query and reached the search results page, indicated by the presence of a total results count.",
    "P3: Detects if the search results page has pagination available, showing that the agent retrieved a multi-page list of products.",
    "P4: Detects the presence of product ASINs (e.g., B01EX1BWE4) in the observation, indicating the agent is viewing actual product listings.",
    "P5: Detects the presence of formatted prices (e.g., $99.99) in the observation, showing the agent is viewing cost information.",
    "P6: Detects if the agent has clicked on a specific product and navigated to its detailed item page, indicated by the '< Prev' navigation button.",
    "P7: Detects if the agent is viewing an item that has selectable attributes (like size, color, or flavor), which are necessary for specifying the exact product variation.",
    "P8: Detects if the agent is viewing the specific price details of an individual item, indicated by the 'Price:' label on the item page.",
    "P9: Detects if the agent is viewing the rating information of the selected item.",
    "P10: Detects if the agent has access to the detailed text description of the item.",
    "P11: Detects if the agent has access to the bulleted features list of the item.",
    "P12: Detects if the agent has access to the customer reviews section of the item.",
    "P13: Detects if the agent has reached a state where the 'Buy Now' button is visible, indicating it is in a position to complete the purchase."
]

def get_webshop_checkpoints() -> list[Callable[[str], bool]]:
    return CHECKPOINTS.copy()

def describe_checkpoints() -> list[tuple[str, str]]:
    return list(zip([f.__name__ for f in CHECKPOINTS], CHECKPOINT_DESCRIPTIONS))
