"""
WebShop State Predicates — Route D (LLM-generated via Gemini API).

Generated by gemini-3-flash-preview from 3 successful + 3 failed trajectories
collected from Qwen2.5-7B-Instruct on WebShop (100 episodes, 4 successes).

API call: scripts/route_d_call_api.py --model gemini-3-flash-preview (2026-03-09)
Raw response: docs/route_d/route_d_response_gemini_20260309_224434.md

These predicates detect ordered state milestones in the WebShop environment.
Original Gemini output adapted for format_obs() quoted observation format
(each [SEP] part wrapped in single quotes) with two bug fixes:
  - P2: "Page 1" hardcode → regex for any page number
  - P4: case mismatch ([SEP] vs [sep] after .lower()) → use plain keywords

Gemini 3 Flash's analysis identified 5 ordered checkpoints:
  1. Search Performed — agent left the landing page
  2. Results Found — search returned product listings
  3. Product Page Reached — agent navigated to a product detail page
  4. Product Options Available — product has configurable options
  5. Purchase Completed — agent reached purchase confirmation
"""

from __future__ import annotations

import re
from typing import Callable


# ============================================================================
# Predicate Definitions (from Gemini 3 Flash, adapted for format_obs)
# ============================================================================

def check_search_performed(observation: str) -> bool:
    """
    P1: Detects if the agent has moved from the initial landing page
    to a search context.

    [Gemini]: "'Back to Search' appears on both the results page and
    product pages."

    Adaptation: case-insensitive substring check.
    """
    return "back to search" in observation.lower()


def check_results_found(observation: str) -> bool:
    """
    P2: Detects if the search query successfully returned a list of products.

    [Gemini]: "Confirmed by the presence of pagination and result counts."
    Original: "Page 1 (Total results:" — hardcoded Page 1.

    Bug fix: use regex for any page number (agent may be on Page 2+).
    """
    return bool(re.search(r'page \d+\s*\(total results:', observation.lower()))


def check_product_page_reached(observation: str) -> bool:
    """
    P3: Detects if the agent has navigated to a specific product detail page.

    [Gemini]: "The 'Buy Now' button only appears on individual product pages."

    Adaptation: case-insensitive substring check.
    """
    return "buy now" in observation.lower()


def check_product_options_available(observation: str) -> bool:
    """
    P4: Detects if the agent is on a product page that offers configurable options.

    [Gemini]: "Common attribute headers in WebShop" — originally checked
    "color [SEP]", "size [SEP]", etc.

    Bug fix: Gemini's original code does observation.lower() which turns
    [SEP] into [sep], but the option patterns contain uppercase [SEP].
    Fix: just check for option keywords as plain substrings (no [SEP]).
    """
    obs = observation.lower()
    if "buy now" not in obs:
        return False
    option_categories = [
        "color", "size", "fit type", "material", "style",
    ]
    return any(cat in obs for cat in option_categories)


def check_purchase_completed(observation: str) -> bool:
    """
    P5: Detects if the agent has clicked 'Buy Now' and reached the
    terminal confirmation page.

    [Gemini]: "'Thank you for shopping with us!' in observation and
    'Purchased' in observation."

    Adaptation: case-insensitive check.
    """
    obs = observation.lower()
    return "thank you for shopping with us!" in obs and "purchased" in obs


# ============================================================================
# Checkpoint List (ordered)
# ============================================================================

WEBSHOP_CHECKPOINTS: list[Callable[[str], bool]] = [
    check_search_performed,          # P1: left landing page
    check_results_found,             # P2: search returned results
    check_product_page_reached,      # P3: navigated to product detail
    check_product_options_available,  # P4: product has configurable options
    check_purchase_completed,        # P5: purchase confirmation reached
]

CHECKPOINT_DESCRIPTIONS = [
    "Navigated away from landing page (Back to Search visible)",
    "Search results successfully returned (Page N, Total results)",
    "Reached product detail page (Buy Now visible)",
    "Product options (size/color/fit/material/style) are visible",
    "Reached purchase confirmation page (Thank you + Purchased)",
]


def get_webshop_checkpoints() -> list[Callable[[str], bool]]:
    """Return the ordered list of WebShop checkpoint predicates."""
    return WEBSHOP_CHECKPOINTS.copy()


def describe_checkpoints() -> list[tuple[str, str]]:
    """Return (function_name, description) for each checkpoint."""
    return [
        (fn.__name__, desc)
        for fn, desc in zip(WEBSHOP_CHECKPOINTS, CHECKPOINT_DESCRIPTIONS)
    ]
