"""
WebShop predicates (failures_only_fine, behavioral, Gemini 3.1 Pro). Auto-generated by route_d_pipeline.py
"""


import re
from typing import Callable

# Predicate functions (ordered by expected progression)

def check_search_page_visited(observation: str) -> bool:
    """P1: Detects if the agent is on the initial search page, the starting point for the task."""
    obs_lower = observation.lower()
    return 'search' in obs_lower and len(observation) < 20

def check_search_results_page(observation: str) -> bool:
    """P2: Detects if the agent has successfully executed a search query and is viewing the search results page."""
    return 'total results:' in observation.lower()

def check_search_results_has_products(observation: str) -> bool:
    """P3: Detects if the search results page contains actual product listings with prices."""
    obs_lower = observation.lower()
    return 'total results:' in obs_lower and '$' in obs_lower

def check_search_results_has_asin(observation: str) -> bool:
    """P4: Detects if the search results page contains product ASINs (Amazon Standard Identification Numbers)."""
    return 'total results:' in observation.lower() and bool(re.search(r'\bb0[a-z0-9]{8}\b', observation, re.IGNORECASE))

def check_search_results_has_next_page(observation: str) -> bool:
    """P5: Detects if the search results contain multiple pages, indicating a broad enough search query."""
    obs_lower = observation.lower()
    return 'total results:' in obs_lower and 'next >' in obs_lower

def check_search_results_page_2_or_more(observation: str) -> bool:
    """P6: Detects if the agent has navigated beyond the first page of search results, showing exploration."""
    return bool(re.search(r'page (?:[2-9]|\d{2,})\s*\(total results:', observation, re.IGNORECASE))

def check_search_results_previous_page_available(observation: str) -> bool:
    """P7: Detects if the agent is on a search results page that allows navigating back to previous pages."""
    obs_lower = observation.lower()
    return 'total results:' in obs_lower and '< prev' in obs_lower

def check_product_page_visited(observation: str) -> bool:
    """P8: Detects if the agent has clicked on a specific product and is viewing its main product page."""
    obs_lower = observation.lower()
    return 'buy now' in obs_lower and 'description' in obs_lower

def check_product_price_visible(observation: str) -> bool:
    """P9: Detects if the product page displays a price, which is necessary for verifying price constraints."""
    obs_lower = observation.lower()
    return 'buy now' in obs_lower and 'price:' in obs_lower

def check_product_options_color(observation: str) -> bool:
    """P10: Detects if the product page has selectable color options, needed for color constraints."""
    obs_lower = observation.lower()
    return 'buy now' in obs_lower and 'color' in obs_lower

def check_product_options_size(observation: str) -> bool:
    """P11: Detects if the product page has selectable size options, needed for size constraints."""
    obs_lower = observation.lower()
    return 'buy now' in obs_lower and 'size' in obs_lower

def check_product_details_page(observation: str) -> bool:
    """P12: Detects if the agent has navigated to a product details page (Description, Features, or Reviews) to read more information."""
    obs_lower = observation.lower()
    return '< prev' in obs_lower and 'buy now' not in obs_lower and 'total results:' not in obs_lower

def check_product_details_has_content(observation: str) -> bool:
    """P13: Detects if the product details page actually contains text content (is not empty), allowing the agent to verify product attributes."""
    obs_lower = observation.lower()
    is_details_page = '< prev' in obs_lower and 'buy now' not in obs_lower and 'total results:' not in obs_lower
    return is_details_page and len(observation) > 50

# Ordered list of all checkpoints
CHECKPOINTS: list[Callable[[str], bool]] = [
    check_search_page_visited,
    check_search_results_page,
    check_search_results_has_products,
    check_search_results_has_asin,
    check_search_results_has_next_page,
    check_search_results_page_2_or_more,
    check_search_results_previous_page_available,
    check_product_page_visited,
    check_product_price_visible,
    check_product_options_color,
    check_product_options_size,
    check_product_details_page,
    check_product_details_has_content
]

CHECKPOINT_DESCRIPTIONS: list[str] = [
    "P1: Detects if the agent is on the initial search page, the starting point for the task.",
    "P2: Detects if the agent has successfully executed a search query and is viewing the search results page.",
    "P3: Detects if the search results page contains actual product listings with prices.",
    "P4: Detects if the search results page contains product ASINs (Amazon Standard Identification Numbers).",
    "P5: Detects if the search results contain multiple pages, indicating a broad enough search query.",
    "P6: Detects if the agent has navigated beyond the first page of search results, showing exploration.",
    "P7: Detects if the agent is on a search results page that allows navigating back to previous pages.",
    "P8: Detects if the agent has clicked on a specific product and is viewing its main product page.",
    "P9: Detects if the product page displays a price, which is necessary for verifying price constraints.",
    "P10: Detects if the product page has selectable color options, needed for color constraints.",
    "P11: Detects if the product page has selectable size options, needed for size constraints.",
    "P12: Detects if the agent has navigated to a product details page (Description, Features, or Reviews) to read more information.",
    "P13: Detects if the product details page actually contains text content (is not empty), allowing the agent to verify product attributes."
]

def get_webshop_checkpoints() -> list[Callable[[str], bool]]:
    return CHECKPOINTS.copy()

def describe_checkpoints() -> list[tuple[str, str]]:
    return list(zip([f.__name__ for f in CHECKPOINTS], CHECKPOINT_DESCRIPTIONS))
